### PR TITLE
simplifying global script

### PR DESCRIPTION
**Pull request by camillegiuliano**
removing some hardcoded defaults and simplifying defining masterRaster's extent

### CODE REVIEW

**Review by eliotmcintire — COMMENTED** [review]
You still need the 
```
paths = list(projectPath = projectPath),
```

**Comment by camillegiuliano** [comment]
Hey @camillegiuliano, while reviewing your PR, I'd suggest the following code changes:

👉 [**restoring paths = list(projectPath = projectPath),**](https://gitkraken.dev/drafts/8078ae1f-8c0c-4d54-bffa-272d4159fd41?source=PRComment)
>

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/8078ae1f-8c0c-4d54-bffa-272d4159fd41?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPTkNlZEVzNkJPMVlDIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

**Comment by camillegiuliano** [comment]
Oops, that's not quite what I wanted gitkraken to do...

**Comment by camillegiuliano** [comment]
Ok, commit restoring `paths = list(projectPath = projectPath),` should be up!

**Pull request merged**
